### ISSUE TITLE
 Expose a  deposit account rest endpoint to create account in the DAS : e13

### ISSUE THREAD

**Issue by Arielpetit** [ADORSYS-GIS/webbank-BankAccount#48]
Complexity: 8

- [ ] Setup a dependency to the deposit account of ledgers
  - [ ] ADORSYS-GIS/webbank-BankAccount#11
  - [ ] ADORSYS-GIS/webank-OnlineBanking#51
  - [ ] ADORSYS-GIS/webank-OnlineBanking#48
  - [ ] ADORSYS-GIS/webank-OnlineBanking#49

**Comment by francis-pouatcha** [comment]
- [ ] Setup a dependency to the deposit account of ledgers
  - [ ] Create a ledgers deposit account rest client if not existing. e5
  - [ ] Use a rest client library to access the module ledger deposit account rest API e3
  - [ ] Unit test with a mock of ledgers deposit account rest api e2
  - [ ] Integration with ledgers as an external component (e.g. testcontainers) e3
